# Generated by Django 3.1.4 on 2022-12-16 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_userfilterdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfilterdata',
            name='gender',
        ),
    ]
