# Generated by Django 3.1.4 on 2022-12-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_userfilterdata_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfilterdata',
            name='height',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
