# Generated by Django 3.1.4 on 2022-12-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20221216_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfilterdata',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userfilterdata',
            name='religion',
        ),
        migrations.AddField(
            model_name='userfilterdata',
            name='interested_age',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userfilterdata',
            name='max_interested_age',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userfilterdata',
            name='relegion',
            field=models.CharField(blank=True, choices=[('Christian', 'Christian'), ('Buddhist', 'Buddhist'), ('Catholic', 'Catholic'), ('Islam', 'Islam'), ('Atheist', 'Atheist'), ('hindui', 'Spirituality')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userfilterdata',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userfilterdata',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userfilterdata',
            name='drink',
            field=models.CharField(blank=True, choices=[('partener_drink_frequently', 'Frequently'), ('partener_drink_socially', 'Socially'), ('partener_drink_never', 'Never')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userfilterdata',
            name='education',
            field=models.CharField(blank=True, choices=[('update_education_college_checkbox', 'College'), ('update_education_highschool_checkbox', 'High School'), ('update_education_BAC_checkbox', 'BAC Level'), ('update_university_checkbox', 'University Diploma')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userfilterdata',
            name='exercise',
            field=models.CharField(blank=True, choices=[('partener_exercise_active', 'Active'), ('partener_exercise_sometime', 'Sometimes'), ('partener_exercise_almostNever', 'Almost Never')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userfilterdata',
            name='kids',
            field=models.CharField(blank=True, choices=[('partener_kids_yes', 'Yes'), ('partener_kids_no', 'No')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userfilterdata',
            name='smoke',
            field=models.CharField(blank=True, choices=[('partener_drink_frequently', 'Frequently'), ('partener_drink_socially', 'Socially'), ('partener_drink_never', 'Never')], max_length=100, null=True),
        ),
    ]
