# Generated by Django 3.1.4 on 2022-12-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20221219_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='remaining_days_in_exp',
            field=models.PositiveSmallIntegerField(blank=True, default=2),
        ),
    ]
